### ISSUE TITLE
Couple of errors in latest "supportJapanese" update

### ISSUE THREAD

**Issue by onimitch** [ThornyFFXI/gdifonts#4]
I came across a couple of errors:

1. If you don't specify `support_jp` in the font settings and `boot.ashita.language` is 1, you get the following error:

Error: gdifonts\fontobject.lua:87: bad argument #3 to 'format' (no value)
```
Error(string.format('The font $H%s$R is not flagged as supporting japanese.  If it does support japanese, please alter the calling addon.  Defaulting to $H%s$R for japanese support.', default_japanese_font));
```
Seems it's just missing the second format arg.

2. Calling set_font_family fails:

Error: ...\ashita\Ashitav4\\addons\balloon\gdifonts\fontobject.lua:91: attempt to index local 'renderer' (a nil value)

```
family = ValidateFont(self.Renderer, family, supportJapanese);
```

I think `self.Renderer` should be `self.renderer`.

Having said all that, I'm not sure whether the support_jp is strictly necessary here.

I did some tests rendering Japanese text in my addon using some different fonts:

Arial

![スクリーンショット 2023-12-15 14 25 48](https://github.com/ThornyFFXI/gdifonts/assets/3901242/c8d00ed9-d396-49dd-89c3-15a50c7e3bd5)

Cambria

![スクリーンショット 2023-12-15 14 27 17](https://github.com/ThornyFFXI/gdifonts/assets/3901242/2a56f4d6-9dc5-4811-80ff-36ac758d0910)

Meiryo

![スクリーンショット 2023-12-15 14 27 51](https://github.com/ThornyFFXI/gdifonts/assets/3901242/f808ba1c-b7ec-4134-a7d7-6a9ffe0866fa)

Noto Sans JP

![スクリーンショット 2023-12-15 14 28 47](https://github.com/ThornyFFXI/gdifonts/assets/3901242/14d48230-232a-4566-bc40-93c2644977b3)

DePixel

![スクリーンショット 2023-12-15 14 30 48](https://github.com/ThornyFFXI/gdifonts/assets/3901242/2479549b-55ba-4f62-bae9-b27642615384)

As you can see from the above, even using a font which doesn't support Japanese, GDI/Windows seems to fallback to rendering with a default font that does support those glyphs. For ref, the japanese text rendered using Arial, Cambria and DePixel above all looks the same.

So far I haven't been able to find a font which does not render.

Actually just to prove for 100% sure, I did the final test with mixed text in the box so you can clearly see the english in pixel style, next to a fallback japanese font all displaying from one font_object render.

![スクリーンショット 2023-12-15 14 35 28](https://github.com/ThornyFFXI/gdifonts/assets/3901242/6533f399-8559-4b2a-a2d6-ce02c1cdabbb)

In Windows, this shows DePixel definitely doesn't support Japanese glyphs:

![スクリーンショット 2023-12-15 14 42 48](https://github.com/ThornyFFXI/gdifonts/assets/3901242/4536a6d1-7faa-4a1c-874e-dd641916c8c3)

Hope this is useful!

**Comment by ThornyFFXI** [comment]
Very useful, I really appreciate all the testing you're putting in.  I want to properly support Japanese as best as possible, but without understanding of the language(nor the intricacies with which font rendering is done), I am not the best person to implement some of these.  I will go back over it and remove the flag, since it does appear windows already maintains a fallback in GDI+.

**Comment by ThornyFFXI** [comment]
Should be resolved.

**Comment by onimitch** [comment]
Just given it a whirl on my addons and all seems good. Thanks!
